Voleska/Controllers/TipiIzdelkovController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Voleska.Data;
using Voleska.Models;
using Voleska.ViewModel;
using Xamarin.Forms.PlatformConfiguration.AndroidSpecific;

using Microsoft.AspNetCore.Http;
using LazZiya.ImageResize;
using Tweetinvi.Controllers.Upload;

namespace Voleska.Controllers
{
    public class TipiIzdelkovController : Controller
    {
        private readonly Data.ApplicationDbContext _context;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public TipiIzdelkovController(Data.ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            WebHostEnvironment = webHostEnvironment;
        }

        // GET: TipiIzdelkov
        public async Task<IActionResult> Index()
        {
            return View(await _context.TipiIzdelkov.ToListAsync());
        }

        // GET: TipiIzdelkov/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipIzdelka = await _context.TipiIzdelkov
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tipIzdelka == null)
            {
                return NotFound();
            }

            return View(tipIzdelka);
        }

        // GET: TipiIzdelkov/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipiIzdelkov/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Ime,Slika")] TipIzdelkaViewModel vm)
        {
            TipIzdelka tipIzdelka = new TipIzdelka();

            if (ModelState.IsValid)
            {
                tipIzdelka.Ime = vm.Ime;
                string imeSlike = UploadFile(vm);
                tipIzdelka.Slika = imeSlike;
                _context.Add(tipIzdelka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipIzdelka);
        }

        private string UploadFile(TipIzdelkaViewModel vm)
        {
            string imeSlike = null;
            if (vm.Slika != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/slike");
                imeSlike = Guid.NewGuid().ToString() + "-" + vm.Slika.FileName;
                string filePath = Path.Combine(uploadDir, imeSlike);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    vm.Slika.CopyTo(fileStream);
                }

                var photo_thumbnail = "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/thumbnail/" + imeSlike;
                ResizeImage(vm.Slika, photo_thumbnail, 100);

                var katalogSlika = "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/katalogSlike/" + imeSlike;
                ResizeImage(vm.Slika, katalogSlika, 290);

            }


            return imeSlike;
        }

        public void ResizeImage(IFormFile uploadedFile, string desiredThumbPath, int desiredWidth = 0, int desiredHeight = 0)
        {
            string webroot = WebHostEnvironment.WebRootPath;

            if (uploadedFile.Length > 0)
            {
                using (var stream = uploadedFile.OpenReadStream())
                {
                    var uploadedImage = System.Drawing.Image.FromStream(stream);

                    //decide how to scale dimensions
                    if (desiredHeight == 0 && desiredWidth > 0)
                    {
                        var img = ImageResize.ScaleByWidth(uploadedImage, desiredWidth); // returns System.Drawing.Image file
                        img.SaveAs(Path.Combine(webroot, desiredThumbPath));
                    }
                    else if (desiredWidth == 0 && desiredHeight > 0)
                    {
                        var img = ImageResize.ScaleByHeight(uploadedImage, desiredHeight); // returns System.Drawing.Image file
                        img.SaveAs(Path.Combine(webroot, desiredThumbPath));
                    }
                    else
                    {
                        var img = ImageResize.Scale(uploadedImage, desiredWidth, desiredHeight); // returns System.Drawing.Image file
                        img.SaveAs(Path.Combine(webroot, desiredThumbPath));
                    }
                }
            }
            return;
        }

        public void DeletePreviousImage(string image)
        {
            string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/slike");
            var imeSlike = image;
            string filePath = Path.Combine(uploadDir, imeSlike);

            string uploadDir2 = Path.Combine(WebHostEnvironment.WebRootPath, "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/thumbnail");
            string filePath2 = Path.Combine(uploadDir2, imeSlike);

            string uploadDir3 = Path.Combine(WebHostEnvironment.WebRootPath, "C:/Users/CRIMSON/source/repos/Voleska/Voleska/wwwroot/katalogSlike");
            string filePath3 = Path.Combine(uploadDir3, imeSlike);

            System.IO.File.Delete(filePath);
            System.IO.File.Delete(filePath2);
            System.IO.File.Delete(filePath3);

        }

        // GET: TipiIzdelkov/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            TipIzdelka tipIzdelka = await _context.TipiIzdelkov
                    .FromSqlRaw(@"SELECT * FROM TipIzdelka WHERE  ID = {0}", id)
                    .AsNoTracking()
                    .FirstOrDefaultAsync();

            TipIzdelkaEditViewModel tipIzdelkaEditViewModel = new TipIzdelkaEditViewModel {
                ID = tipIzdelka.ID,
                Ime = tipIzdelka.Ime,
                
                ObstojecaSlika = tipIzdelka.Slika
                
            
            };
            return View(tipIzdelkaEditViewModel);
        }

        // POST: TipiIzdelkov/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Ime, Slika")] TipIzdelkaViewModel vm)
        {
            var tipIzdelka = await _context.TipiIzdelkov
                    .FromSqlRaw(@"SELECT * FROM TipIzdelka WHERE  ID = {0}", id)
                    .AsNoTracking()
                    .FirstOrDefaultAsync();

            if (id != tipIzdelka.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tipIzdelka.Ime = vm.Ime;
                    string imeSlike = UploadFile(vm);
                    if (imeSlike != null)
                    {
                        DeletePreviousImage(tipIzdelka.Slika);
                        tipIzdelka.Slika = imeSlike;
                    }
                    

                    _context.Update(tipIzdelka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipIzdelkaExists(tipIzdelka.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipIzdelka);
        }

        // GET: TipiIzdelkov/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipIzdelka = await _context.TipiIzdelkov
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tipIzdelka == null)
            {
                return NotFound();
            }

            return View(tipIzdelka);
        }

        // POST: TipiIzdelkov/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipIzdelka = await _context.TipiIzdelkov.FindAsync(id);

            DeletePreviousImage(tipIzdelka.Slika);

            _context.TipiIzdelkov.Remove(tipIzdelka);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipIzdelkaExists(int id)
        {
            return _context.TipiIzdelkov.Any(e => e.ID == id);
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> Preveri(string ime, string tip)
        {
            if (tip == null)
            {
                var tipiIzdelkov = from m in _context.TipiIzdelkov
                                   select m;


                tipiIzdelkov = tipiIzdelkov.Where(s => s.Ime == ime);

                if (tipiIzdelkov.Any())
                {

                    return Json(true);
                }
                else
                {

                    return Json(false);
                }
            }
            else {
                var tipiIzdelkov = from m in _context.TipiIzdelkov
                                   select m;

Voleska/Views/TipiIzdelkov/Create.cshtml
@model Voleska.ViewModel.TipIzdelkaViewModel

@{
    ViewData["Title"] = "Ustvari";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="TipiIzdelkov"  class="customColor">Tipi izdelkov</a></li>
        <li class="breadcrumb-item active">Ustvari</li>
    </ol>
</nav>

<h1 class="text-center mb-4">Ustvari tip izdelka</h1>

<hr />
<div class="row d-flex justify-content-center">
    <div class="col-md-4 d-flex justify-content-center">
        <form asp-action="Create" enctype="multipart/form-data" class="needs-validation" novalidate>
           
            <div class="form-group md-form md-outline">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control z-depth-1" required />
                
                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    <span id="errorMessage">Ime je obvezno!</span>
                </div>
            </div>
          

            <div class="no-display" id="prikazSlike">
                <img id="output" src="~/katalogSlike/" asp-append-version="true" class="z-depth-1 img-thumbnail d-flex justify-content-center" width="290" />
            </div>        
            <div class="input-group z-depth-1">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="slika">Naloži</span>
                </div>
                <div class="custom-file ">
                    <input type="file" class="custom-file-input" id="slika"
                           aria-describedby="slika" asp-for="Slika" required >
                    <label class="custom-file-label" asp-for="Slika">Izberite datoteko...</label>
                </div>
                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    Slika je obvezna!
                </div>
            </div>
            
            <div class="form-group d-flex justify-content-center mt-5 mb-0">
                <input type="submit" value="Ustvari" class="btn btn-cyan" />
            </div>
        </form>
    </div>
    
</div>

<div class="text-center">
    <a asp-action="Index" class="customColor">Nazaj na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>


        $(document).ready(function () {


            $('input[type="file"]').change(function () {
                $('#prikazSlike').removeClass("animated fadeIn");
                $('#prikazSlike').addClass("d-flex justify-content-center mb-4");
                readURL(this);
            });


            $('input[type="text"]').on('change keyup paste', function (event) {
                validirajAjax(event);
            });
        });




        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#output').attr('src', e.target.result);
                    $('#prikazSlike').removeClass("animated fadeOut");
                    $('#prikazSlike').addClass("animated fadeIn");
                    $('#prikazSlike').removeClass("no-display");
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }


        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {

                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

    function validirajAjax(vrednostInput) {
        var vrednost = vrednostInput.target.value;
        
        $.ajax({
            type: "POST",
            url: '@Url.Action("Preveri", "TipiIzdelkov")',
            data: { ime: vrednost },
            success: function (data) {

                
                if (data) {

                   
                    $('#errorMessage').text("Ime že obstaja!");
                   
                    vrednostInput.target.setCustomValidity('Bla bla');
                } else {
                    
                    $('#errorMessage').text("Ime je obvezno!");
                   
                    vrednostInput.target.setCustomValidity('');
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
</script>
}

Voleska/Views/TipiIzdelkov/Delete.cshtml
@model Voleska.Models.TipIzdelka

@{
    ViewData["Title"] = "Izbriši";
}
<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="TipiIzdelkov" class="customColor">Tipi izdelkov</a></li>
        <li class="breadcrumb-item active">Izbriši</li>
    </ol>
</nav>
<h1 class="text-danger text-center">Izbriši</h1>

<h3 class="text-center">Izbrišem tip izdelka "@Html.DisplayFor(model => model.Ime)"?</h3>
<hr />
<div class="justify-content-center d-flex my-4">
    <img src="~/katalogSlike/@Model.Slika" alt="thumbnail" class="img-thumbnail z-depth-1">
</div>

<div class="d-flex justify-content-center">   
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Izbriši" class="btn btn-danger" />
        
    </form>
</div>
<a asp-action="Index" class="d-flex justify-content-center customColor">Nazaj na seznam</a>

Voleska/Views/TipiIzdelkov/Details.cshtml
@model Voleska.Models.TipIzdelka

@{
    ViewData["Title"] = "Podrobnosti";
}
<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="TipiIzdelkov" class="customColor">Tipi izdelkov</a></li>
        <li class="breadcrumb-item active">Podrobnosti</li>
    </ol>
</nav>
<h1 class="text-center">@Html.DisplayFor(model => model.Ime)</h1>
<hr />
<div>
    <div class="justify-content-center d-flex my-4">
        <img src="~/katalogSlike/@Model.Slika" alt="thumbnail" class="img-thumbnail z-depth-1">
    </div>
</div>
<div class="d-flex justify-content-center">
    <a asp-action="Edit" asp-route-id="@Model.ID" class="mr-1 customColor">Uredi</a> |
    <a asp-action="Index" class="ml-1 customColor">Nazaj na seznam</a>
</div>

Voleska/Views/TipiIzdelkov/Edit.cshtml
@model Voleska.ViewModel.TipIzdelkaEditViewModel

@{
    ViewData["Title"] = "Uredi";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="TipiIzdelkov" class="customColor">Tipi izdelkov</a></li>
        <li class="breadcrumb-item active">Uredi</li>
    </ol>
</nav>

<h1 class="text-center mb-2">Uredi tip izdelka</h1>
<hr />
<div class="row justify-content-center d-flex">
    
        <div class="col-md-7 justify-content-center d-flex">
                 <input type="hidden" value="@Model.Ime" class="no-display" id="trenutniTipIzdelka"/>

                 <form asp-action="Edit" enctype="multipart/form-data" class="needs-validation" novalidate>
                     <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                     <input type="hidden" asp-for="ID" />
                     <div class="form-group md-form md-outline">
                         <label asp-for="Ime" class="control-label"></label>

                         <input asp-for="Ime" class="form-control z-depth-1" required />


                         <div class="valid-tooltip">
                             Izgleda okej!
                         </div>
                         <div class="invalid-tooltip">
                             <span id="errorMessage">Ime je obvezno!</span>
                         </div>
                     </div>
                     <div id="prikazSlike">
                         <img id="output" src="~/katalogSlike/@Model.ObstojecaSlika" asp-append-version="true" class="z-depth-1 img-thumbnail d-flex justify-content-center" width="290"/>
                     </div>
                    <div class="form-group pt-2 d-flex justify-content-center">
                        <label for="slika" class="mt-2 btn-sm btn-outline-info control-label">Spremeni sliko</label>
                        <input type="file" accept="image/*" onchange="loadFile(event)" asp-for="Slika" id="slika" class="form-control" style="display:none" />
                        <span asp-validation-for="Slika" class="text-danger"></span>
                    </div>



                         <div class="form-group d-flex justify-content-center mb-0">
                             <input type="submit" value="Shrani spremembe" class="btn btn-primary" />
                         </div>
                         <div class="justify-content-center d-flex">
                             <a asp-action="Index" class="text-center customColor">Nazaj na seznam</a>
                         </div>

                 </form>
           
        </div>
       
    
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>


        $(document).ready(function () {


            $('input[type="file"]').change(function () {
                $('#prikazSlike').removeClass("animated fadeIn");
                $('#prikazSlike').addClass("d-flex justify-content-center mb-4");
                readURL(this);
            });


            $('input[type="text"]').on('change keyup paste', function (event) {
                validirajAjax(event);
            });
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#output').attr('src', e.target.result);
                    $('#prikazSlike').removeClass("animated fadeOut");
                    $('#prikazSlike').addClass("animated fadeIn");
                    $('#prikazSlike').removeClass("no-display");
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }

        function validirajAjax(vrednostInput) {
            var vrednost = vrednostInput.target.value;
            var tip = $("#trenutniTipIzdelka").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Preveri", "TipiIzdelkov")',
                data: { ime: vrednost, tip: tip },
                success: function (data) {


                    if (data) {

                       
                        $('#errorMessage').text("Ime že obstaja!");
                        $('input[type="text"]').removeClass("valid");
                        $('input[type="text"]').addClass("input-validation-error");
                        vrednostInput.target.setCustomValidity('Ime že obstaja!');
                    } else {

                        $('#errorMessage').text("Ime je obvezno!");

                        vrednostInput.target.setCustomValidity('');
                    }

                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }



        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {

                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

</script>
}

Voleska/Views/TipiIzdelkov/Index.cshtml
@model IEnumerable<Voleska.Models.TipIzdelka>

@{
    ViewData["Title"] = "Tipi izdelkov";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item active">Tipi izdelkov</li>
    </ol>
</nav>
<h1 class="text-center mb-3">Tipi izdelkov</h1>

<p>
    <a asp-action="Create" class="customColor"><i class="far fa-plus-square fa-lf mr-2"></i>Ustvari nov tip izdelka</a>
</p>
@{
    var stevec = 1;
    var animacija = "";
}
<div class="row">
    @foreach (var item in Model)
    {
        @if (stevec % 2 == 0)
        {
            animacija = "animated fadeInRight";
        }
        else {
            animacija = "animated fadeInLeft";
        }
    <div class="col-12 my-3 @animacija fast">
        <!-- Card
    <div class="card card-image" style="background: url(/katalogSlike/@item.Slika) no-repeat;">
    -->
        <div class="card bg-light">
            <div class="card-body d-flex align-items-center">
                <h5 class="card-title align-self-center p-0 mb-0">@Html.DisplayFor(modelItem => item.Ime)</h5>
                <div class="ml-auto">
                    <a asp-action="Edit" asp-route-id="@item.ID" class="card-link customColor">Uredi</a>
                    <a asp-action="Details" asp-route-id="@item.ID" class="card-link customColor">Podrobnosti</a>
                    <a asp-action="Delete" asp-route-id="@item.ID" class="card-link customColor">Izbriši</a>
                </div>
                
            </div>
        </div>

    </div>

        stevec += 1;



    }
</div>

<div class="d-flex"><a class="nav-link customColor pl-0 mt-2" asp-area="" asp-controller="Izdelki" asp-action="Index"><i class="fas fa-pen-square fa-lf mr-2"></i>Urejanje izdelkov</a></div>