Voleska/Controllers/MaterialiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Voleska.Data;
using Voleska.Models;

namespace Voleska.Controllers
{
    public class MaterialiController : Controller
    {
        private readonly Data.ApplicationDbContext _context;

        public MaterialiController(Data.ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Materiali
        public async Task<IActionResult> Index()
        {
            ViewData["NumberOf"] = _context.Materiali.ToList().Count();

            return View(await _context.Materiali.ToListAsync());
        }

        // GET: Materiali/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materiali
                .FirstOrDefaultAsync(m => m.ID == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // GET: Materiali/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Materiali/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Ime,Opis")] Material material)
        {
            if (ModelState.IsValid)
            {
                _context.Add(material);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        // GET: Materiali/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materiali.FindAsync(id);
            if (material == null)
            {
                return NotFound();
            }
            return View(material);
        }

        // POST: Materiali/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Ime,Opis")] Material material)
        {
            if (id != material.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(material);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaterialExists(material.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        // GET: Materiali/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.Materiali
                .FirstOrDefaultAsync(m => m.ID == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // POST: Materiali/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var material = await _context.Materiali.FindAsync(id);
            _context.Materiali.Remove(material);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialExists(int id)
        {
            return _context.Materiali.Any(e => e.ID == id);
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> PreveriIme(string ime, string tip)
        {
            if (tip == null)
            {
                var materiali = from m in _context.Materiali
                                   select m;


                materiali = materiali.Where(s => s.Ime == ime);

                if (materiali.Any())
                {

                    return Json(true);
                }
                else
                {

                    return Json(false);
                }
            }
            else
            {
                var materiali = from m in _context.Materiali
                                select m;


                materiali = materiali.Where(s => s.Ime == ime && s.Ime != tip);

                if (materiali.Any())
                {

                    return Json(true);
                }
                else
                {

                    return Json(false);
                }
            }


        }

       
    }
}

Voleska/Views/Materiali/Create.cshtml
@model Voleska.Models.Material

@{
    ViewData["Title"] = "Ustvari";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Materiali" class="customColor">Materiali</a></li>
        <li class="breadcrumb-item active">Ustvari</li>
    </ol>
</nav>
<h1 class="text-center mb-4">Ustvari material</h1>

<hr />
<div class="row d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" class="needs-validation" novalidate id="registracijaObrazec">

            <div class="form-group md-form md-outline">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control z-depth-1 p-2 pl-3 mb-5" required />

                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    <span id="errorMessage">Ime je obvezno!</span>
                </div>
            </div>

            <div class="md-form md-outline form-group shadow-textarea">

                <textarea asp-for="Opis" class="md-textarea form-control p-3 z-depth-1" rows="3" required></textarea>
                <label asp-for="Opis" class="control-label mt-2">Opis materiala</label>
                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    Opis je obvezen!
                </div>
            </div>


            <div class="form-group d-flex justify-content-center mt-5 mb-0">
                <input type="submit" value="Ustvari" class="btn btn-cyan" />
            </div>
        </form>
    </div>

</div>

<div class="text-center">
    <a asp-action="Index" class="customColor">Nazaj na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>


            $(document).ready(function () {


                $("#registracijaObrazec").find('input:visible:first').on('change keyup paste', function (event) {
                        validirajAjax(event);
                });

            });


            function validirajAjax(vrednostInput) {
                var vrednost = vrednostInput.target.value;
                var tip = $("#trenutniMaterial").val();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("PreveriIme", "Materiali")',
                    data: { ime: vrednost, tip: tip },
                    success: function (data) {


                        if (data) {


                            $('#errorMessage').text("Ime že obstaja!");
                            $("#registracijaObrazec").find('input:visible:first').removeClass("valid");
                            $("#registracijaObrazec").find('input:visible:first').addClass("input-validation-error");
                            vrednostInput.target.setCustomValidity('Ime že obstaja!');
                        } else {

                            $('#errorMessage').text("Ime je obvezno!");

                            vrednostInput.target.setCustomValidity('');
                        }

                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            }



            (function () {
                'use strict';
                window.addEventListener('load', function () {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function (form) {
                        form.addEventListener('submit', function (event) {
                            if (form.checkValidity() === false) {

                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();

    </script>
}

Voleska/Views/Materiali/Delete.cshtml
@model Voleska.Models.Material

@{
    ViewData["Title"] = "Izbriši";
}
<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Materiali" class="customColor">Materiali</a></li>
        <li class="breadcrumb-item active">Izbriši</li>
    </ol>
</nav>

<h1 class="text-danger text-center">Izbriši</h1>

<h3 class="text-center">Izbrišem material "@Html.DisplayFor(model => model.Ime)"?</h3>
<hr />
<div class="row d-flex justify-content-center">
    
    <div class="card bg-light mt-4 mb-5" style="max-width: 20rem;">
        <div class="card-header">@Html.DisplayFor(model => model.Ime)</div>
        <div class="card-body">
            
            <p class="card-text"> @Html.DisplayFor(model => model.Opis)</p>
        </div>
    </div>
</div>


<div class="d-flex justify-content-center">
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Izbriši" class="btn btn-danger" />

    </form>
</div>
<a asp-action="Index" class="d-flex justify-content-center customColor">Nazaj na seznam</a>

Voleska/Views/Materiali/Details.cshtml
@model Voleska.Models.Material

@{
    ViewData["Title"] = "Podrobnosti";
}
<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Materiali" class="customColor">Materiali</a></li>
        <li class="breadcrumb-item active">Podrobnosti</li>
    </ol>
</nav>

<h1 class="text-center">@Html.DisplayFor(model => model.Ime)</h1>
<hr />
<div class="d-flex justify-content-center">

    <div class="card bg-light mt-4 mb-5" style="max-width: 20rem;">
        <div class="card-header">@Html.DisplayFor(model => model.Ime)</div>
        <div class="card-body">

            <p class="card-text"> @Html.DisplayFor(model => model.Opis)</p>
        </div>
    </div>
</div>

<div class="d-flex justify-content-center">
    <a asp-action="Edit" asp-route-id="@Model.ID" class="mr-1 customColor">Uredi</a> |
    <a asp-action="Index" class="ml-1 customColor">Nazaj na seznam</a>
</div>

Voleska/Views/Materiali/Edit.cshtml
@model Voleska.Models.Material

@{
    ViewData["Title"] = "Uredi";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Materiali" class="customColor">Materiali</a></li>
        <li class="breadcrumb-item active">Uredi</li>
    </ol>
</nav>

<h1 class="text-center mb-2">Uredi material</h1>
<hr />
<div class="row justify-content-center d-flex">

    <div class="col-md-4">
        <input type="hidden" value="@Model.Ime" class="no-display" id="trenutniMaterial" />

        <form asp-action="Edit" enctype="multipart/form-data" class="needs-validation" novalidate id="registracijaObrazec">

            <div class="form-group md-form md-outline mt-3 mb-5">
                <label asp-for="Ime" class="control-label"></label>

                <input asp-for="Ime" class="form-control z-depth-1 p-2 pl-3" required />


                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    <span id="errorMessage">Ime je obvezno!</span>
                </div>
            </div>
            
            <div class="md-form md-outline form-group shadow-textarea">
                
                <textarea asp-for="Opis" class="md-textarea form-control p-3 z-depth-1" rows="3" required></textarea>
                <label asp-for="Opis" class="control-label mt-2">Opis materiala</label>
                <div class="valid-tooltip">
                    Izgleda okej!
                </div>
                <div class="invalid-tooltip">
                    Opis je obvezen!
                </div>
            </div>
                
            

            
            <input type="hidden" asp-for="ID" />

            <div class="form-group d-flex justify-content-center mb-0">
                <input type="submit" value="Shrani spremembe" class="btn btn-primary" />
            </div>
            <div class="justify-content-center d-flex">
                <a asp-action="Index" class="text-center customColor">Nazaj na seznam</a>
            </div>

        </form>

    </div>


</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>


        $(document).ready(function () {


            $("#registracijaObrazec").find('input:visible:first').on('change keyup paste', function (event) {
                    validirajAjax(event);
            });

        });

  
        function validirajAjax(vrednostInput) {
            var vrednost = vrednostInput.target.value;
            var tip = $("#trenutniMaterial").val();
            
            $.ajax({
                type: "POST",
                url: '@Url.Action("PreveriIme", "Materiali")',
                data: { ime: vrednost, tip: tip },
                success: function (data) {


                    if (data) {


                        $('#errorMessage').text("Ime že obstaja!");
                        $("#registracijaObrazec").find('input:visible:first').removeClass("valid");
                        $("#registracijaObrazec").find('input:visible:first').addClass("input-validation-error");
                        vrednostInput.target.setCustomValidity('Ime že obstaja!');
                    } else {

                        $('#errorMessage').text("Ime je obvezno!");

                        vrednostInput.target.setCustomValidity('');
                    }

                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }



        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {

                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

</script>
}

Voleska/Views/Materiali/Index.cshtml
@model IEnumerable<Voleska.Models.Material>

@{
    ViewData["Title"] = "Materiali";
}

<nav aria-label="breadcrumb" class="">
    <ol class="breadcrumb bg-white d-flex justify-content-center">
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-izbira="domov" class="customColor">Domov</a></li>
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Katalog" asp-action="Index" class="customColor">Katalog</a></li>
        <li class="breadcrumb-item active">Materiali</li>
    </ol>
</nav>

<h1 class="text-center mb-3">Materiali</h1>

<p>
    <a asp-action="Create" class="customColor"><i class="far fa-plus-square fa-lf mr-2"></i>Ustvari nov material</a>
</p>
@{
    var stevec = 1;
    var animacija = "";
    var visina = "";
}
@if(ViewBag.NumberOf <3){
    visina = "zapolniStran";
}
<div class="row @visina">
    @foreach (var item in Model)
    {
        @if (stevec % 2 == 0)
        {
            animacija = "animated fadeInRight";
        }
        else
        {
            animacija = "animated fadeInLeft";
        }
        <div class="col-12 my-3 @animacija fast">
            <div class="card bg-light">
                <div class="card-body d-flex align-items-center">
                    <h5 class="card-title align-self-center p-0 mb-0">@Html.DisplayFor(modelItem => item.Ime)</h5>
                    <div class="ml-auto">
                        <a asp-action="Edit" asp-route-id="@item.ID" class="card-link customColor">Uredi</a>
                        <a asp-action="Details" asp-route-id="@item.ID" class="card-link customColor">Podrobnosti</a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="card-link customColor">Izbriši</a>
                    </div>

                </div>
            </div>

        </div>

        stevec += 1;



    }
</div>

<div class="d-flex"><a class="nav-link customColor pl-0 " asp-area="" asp-controller="Izdelki" asp-action="Index"><i class="fas fa-pen-square fa-lf mr-2"></i>Urejanje izdelkov</a></div>